theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 40

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/mnt/dev/"
alias = "/dev"
info_type = "available"
unit = "TB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "enp2s0"
speed_up = true
speed_down = true
interval = 1
use_bits = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
